### ISSUE TITLE
Non-static method Error

### ISSUE THREAD

**Issue by christophschoeni** [vluzrmos/laravel-slack-api#20]
Hi Guys 
Thanks for you repo, its amazing and save many time. But i have a problem in my projects. Am I doing something wrong?

```php
namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Vluzrmos\SlackApi\Contracts\SlackUser;

class SlackController extends Controller
{
    /** @var  SlackUser */
    protected $slackUser;

    public function __construct(SlackUser as $slackUser){
        $this->slackUser = $slackUser;   
    }
    
    public function test()
    {
        $usersList = $this->slackUser->lists();
        dd($usersList);
    }
...
```
When i start this with my lidle testCase then i became this Error:

Symfony\Component\Debug\Exception\FatalThrowableError thrown with message "Non-static method Vluzrmos\SlackApi\Contracts\SlackUser::all() cannot be called statically"  Stacktrace: #0 Symfony\Component\Debug\Exception\FatalThrowableError in /var/www/app/Http/Controllers/SlackController.php:21

Thanks and best regards
Christoph

**Comment by lucasvieirawerner** [comment]
ac

**Comment by vluzrmos** [comment]
Closing due to very old issue.
