### ISSUE TITLE
Get response whether SlackUserAdmin::invite worked or not?

### ISSUE THREAD

**Issue by reillychase** [vluzrmos/laravel-slack-api#22]
This doesn't work:

Route::get('v1/slack/invite', function () {
	//Invite a new member to your team
	$resp = SlackUserAdmin::invite("rchase@captifi.net");
	return $resp;
});

Is there a way to get a response like "OK" or "Already invited"?

**Comment by vluzrmos** [comment]
See the section "Errors" on [Admin Users Invite](https://api.slack.com/methods/admin.users.invite)

It will respond with 

```jsonc
{
  "error": "already_in_team_invited_user" // or "already_in_team" ...
}
```
