### ISSUE TITLE
Always getting invalid_auth

### ISSUE THREAD

**Issue by isaac-manubag** [vluzrmos/laravel-slack-api#30]
All my requests are getting invalid auth. I have hardcoded the `Bot Token` onto my `services.php` config file as per documentation.

On my Slack App - the `Bot` has the `chat:write` OAuth Scope enabled.

Usage is simply just like this

```
$test = slack()->post('chat.postMessage', [
        'channel' => '#test-channel',
        'text' => 'Isaac'
    ]);

dd(1, $test);
```

and on the browser i get
![image](https://user-images.githubusercontent.com/8652190/109376717-6b79ba80-7901-11eb-91f0-d679ce2d4580.png)

Im using Laravel 7.3 and vluzrmos/laravel-slack-api:0.5.0
PHP 7.3

**Comment by huiyang** [comment]
I face the same issue, was thought it is my mistake

**Comment by huiyang** [comment]
I tried this package 
https://packagist.org/packages/jolicode/slack-php-api

and it is working.

**Comment by vluzrmos** [comment]
Hi @isaac-manubag , I tried to simulate that error, but only receive "missing_scope".

![image](https://user-images.githubusercontent.com/450848/111839491-a1470900-88d9-11eb-96dc-3824271e1aad.png)

Which means that I have to add the new scope to my app. I did it but it is only available to enterprise plans.

I think you may have some typo in your configuration files.

**Comment by lukassivak** [comment]
I am facing exactly the same "invalid_auth" issue. If i change the package to https://packagist.org/packages/jolicode/slack-php-api it works, no error with the "invalid_auth". So far i wasn't able to identify the root cause.

**Comment by cgunnels** [comment]
Anyone figure this out?

**Comment by peterjaap** [comment]
Same here.

**Comment by vluzrmos** [comment]
Hi everyone, it may be causing error because the package was sending the authorization token on the request query #32 .

Please, try again with version v0.5.1.
