### ISSUE TITLE
There seems to be a policy change in slack..

### ISSUE THREAD

**Issue by kslee0115** [vluzrmos/laravel-slack-api#32]
Thank you for your hard work.
There seems to be a policy change in slack.
Instead of including the token as a parameter, it seems to work only if it is placed in the header.
Would it be possible to modify it and distribute it?
Thank you.

* Below are the relevant updates from Slack.
https://api.slack.com/changelog/2020-11-no-more-tokens-in-querystrings-for-newly-created-apps

**Comment by vluzrmos** [comment]
Thanks @kslee0115 , I resolve that issue on the release v0.5.1
