### ISSUE TITLE
SlackOAuthV2 facade can't work.

### ISSUE THREAD

**Issue by manavu** [vluzrmos/laravel-slack-api#33]
getFacadeAccessor method returned name is different.
``` 
slack.oauthv2
```
but registration name is
```
slack.o_auth_v2
```
Cause is Str::snake method.

**Comment by vluzrmos** [comment]
Resolvido na versão v0.5.2

https://github.com/vluzrmos/laravel-slack-api/releases/tag/v0.5.2
