### ISSUE TITLE
Deprecating antecedents to the conversations api

### ISSUE THREAD

**Issue by JBtje** [vluzrmos/laravel-slack-api#34]
I want to use this package, to remove all messages from a specific logs channel. However, the channels I use are recently created and the example below results in a method_deprecated error.
```php
$channel = slack()->load('Channel');
dd( $channel->lists() );
```

```
{#1351
  +"ok": false
  +"error": "method_deprecated"
  +"response_metadata": {#1349
    +"messages": array:1 [
      0 => "[ERROR] This method is retired and can no longer be used. Please use conversations.list or users.conversations instead. Learn more: https://api.slack.com/changelog/2020-01-deprecating-antecedents-to-the-conversations-api."
    ]
  }
}
```

https://api.slack.com/changelog/2020-01-deprecating-antecedents-to-the-conversations-api#prepare

I believe these changes have not been implemented yet?

**Comment by mostafasoufi** [comment]
The issue can be closed since the PR has been merged.
